-- Rollback for part 1 of customer_portal.sql on STAGING (ekgdefcdqcsqvpbqponv).
-- Restores the exact Ops policy expressions captured on 2026-09-24 before hardening.
-- WARNING: restoring these re-opens Ops data to any signed-in customer. Only use it while
-- customer sign-up is disabled. Production needs its own snapshot (see CUSTOMER-PORTAL.md).
--
-- To capture the same snapshot on another project BEFORE applying customer_portal.sql, run:
--   select string_agg(format('alter policy %I on %I.%I%s%s;', policyname, schemaname, tablename,
--            case when qual is not null then format(' using (%s)', qual) else '' end,
--            case when with_check is not null then format(' with check (%s)', with_check) else '' end),
--          E'\n' order by schemaname, tablename, policyname)
--   from pg_policies
--   where (schemaname = 'public' or (schemaname = 'storage' and tablename = 'objects'))
--     and ('authenticated' = any (roles) or 'public' = any (roles));
begin;
alter policy activity_log_insert on public.activity_log with check (true);
alter policy activity_log_select on public.activity_log using (true);
alter policy ai_plans_insert on public.ai_plans with check (true);
alter policy ai_plans_select on public.ai_plans using (true);
alter policy admin_read on public.audit_log using (is_finance_admin());
alter policy cash_recons_insert on public.cash_recons with check (is_mgr());
alter policy cash_recons_select on public.cash_recons using (true);
alter policy "manager read errors" on public.client_errors using (is_manager());
alter policy "staff insert errors" on public.client_errors with check (is_active_staff());
alter policy customers_insert on public.customers with check (true);
alter policy customers_select on public.customers using (true);
alter policy customers_update on public.customers using (true) with check (true);
alter policy "manager delete customers" on public.customers using (is_manager());
alter policy "staff add customers" on public.customers with check (is_active_staff());
alter policy "staff edit customers" on public.customers using (is_active_staff()) with check (is_active_staff());
alter policy "staff insert customers" on public.customers with check (is_active_staff());
alter policy "staff read customers" on public.customers using (is_active_staff());
alter policy "staff update customers" on public.customers using (is_active_staff()) with check (is_active_staff());
alter policy "targets read" on public.dashboard_targets using (true);
alter policy "targets write" on public.dashboard_targets using (true) with check (true);
alter policy device_tokens_delete_own on public.device_tokens using ((user_id = auth.uid()));
alter policy device_tokens_insert_own on public.device_tokens with check ((user_id = auth.uid()));
alter policy device_tokens_select_own on public.device_tokens using ((user_id = auth.uid()));
alter policy device_tokens_update_own on public.device_tokens using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
alter policy admin_all on public.employees using (is_finance_admin()) with check (is_finance_admin());
alter policy read_all on public.expense_attachments using (true);
alter policy staff_insert on public.expense_attachments with check (true);
alter policy admin_all on public.expense_categories using (is_finance_admin()) with check (is_finance_admin());
alter policy read_all on public.expense_categories using (true);
alter policy expenses_delete on public.expenses using ((is_admin() OR (created_by = auth.uid())));
alter policy expenses_insert on public.expenses with check ((is_manager() AND (created_by = auth.uid())));
alter policy expenses_select on public.expenses using ((is_admin() OR (created_by = auth.uid())));
alter policy expenses_update on public.expenses using ((is_admin() OR (created_by = auth.uid()))) with check ((is_admin() OR (created_by = auth.uid())));
alter policy admin_del on public.expenses_backup_20260802112552 using (is_finance_admin());
alter policy admin_write on public.expenses_backup_20260802112552 using (is_finance_admin());
alter policy read_all on public.expenses_backup_20260802112552 using (true);
alter policy staff_insert on public.expenses_backup_20260802112552 with check (true);
alter policy feedback_insert on public.feedback with check (true);
alter policy feedback_select on public.feedback using (true);
alter policy floor_issues_insert on public.floor_issues with check (true);
alter policy floor_issues_select on public.floor_issues using (true);
alter policy floor_issues_update on public.floor_issues using (true) with check (true);
alter policy iron_board_counts_del on public.iron_board_counts using (true);
alter policy iron_board_counts_ins on public.iron_board_counts with check (true);
alter policy iron_board_counts_sel on public.iron_board_counts using (true);
alter policy iron_board_counts_upd on public.iron_board_counts using (true) with check (true);
alter policy "kpi insert" on public.kpi_events with check (is_active_staff());
alter policy "kpi manager purge" on public.kpi_events using (is_manager());
alter policy "kpi read" on public.kpi_events using (is_active_staff());
alter policy "manager write targets" on public.monthly_targets using (is_manager()) with check (is_manager());
alter policy "monthly_targets read" on public.monthly_targets using (true);
alter policy "monthly_targets write" on public.monthly_targets using ((EXISTS ( SELECT 1 FROM profiles WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'manager'::text])) AND (profiles.active = true)))));
alter policy "staff read targets" on public.monthly_targets using (is_active_staff());
alter policy "staff add order items" on public.order_items with check (is_active_staff());
alter policy "staff edit order items" on public.order_items using (is_active_staff()) with check (is_active_staff());
alter policy "staff read order items" on public.order_items using (is_active_staff());
alter policy "staff read order_items" on public.order_items using (is_active_staff());
alter policy "staff write order_items" on public.order_items using (is_active_staff()) with check (is_active_staff());
alter policy "manager delete order_photos" on public.order_photos using (is_manager());
alter policy "staff add order photos" on public.order_photos with check (is_active_staff());
alter policy "staff insert order_photos" on public.order_photos with check (is_active_staff());
alter policy "staff read order photos" on public.order_photos using (is_active_staff());
alter policy "staff read order_photos" on public.order_photos using (is_active_staff());
alter policy order_risks_insert on public.order_risks with check (true);
alter policy order_risks_select on public.order_risks using (true);
alter policy "stains insert" on public.order_stains with check (true);
alter policy "stains manager purge" on public.order_stains using (is_manager());
alter policy "stains select" on public.order_stains using (true);
alter policy "stains staff insert" on public.order_stains with check (is_active_staff());
alter policy "stains staff read" on public.order_stains using (is_active_staff());
alter policy "stains update" on public.order_stains using (true) with check (true);
alter policy "staff read status history" on public.order_status_history using (is_active_staff());
alter policy "manager delete orders" on public.orders using (is_manager());
alter policy orders_insert on public.orders with check (true);
alter policy orders_select on public.orders using (true);
alter policy orders_update on public.orders using (true) with check (true);
alter policy "staff add orders" on public.orders with check (is_active_staff());
alter policy "staff edit orders" on public.orders using (is_active_staff()) with check (is_active_staff());
alter policy "staff insert orders" on public.orders with check (is_active_staff());
alter policy "staff read orders" on public.orders using (is_active_staff());
alter policy "staff write orders" on public.orders using (is_active_staff()) with check (is_active_staff());
alter policy outlet_targets_insert on public.outlet_targets with check (is_mgr());
alter policy outlet_targets_select on public.outlet_targets using (true);
alter policy outlet_targets_update on public.outlet_targets using (is_mgr()) with check (is_mgr());
alter policy outlets_select on public.outlets using (true);
alter policy admin_all on public.outlets_backup_20260801214035 using (is_finance_admin()) with check (is_finance_admin());
alter policy read_all on public.outlets_backup_20260801214035 using (true);
alter policy outsource_assignments_del on public.outsource_assignments using (true);
alter policy outsource_assignments_ins on public.outsource_assignments with check (true);
alter policy outsource_assignments_sel on public.outsource_assignments using (true);
alter policy outsource_assignments_upd on public.outsource_assignments using (true) with check (true);
alter policy outsource_partners_del on public.outsource_partners using (true);
alter policy outsource_partners_ins on public.outsource_partners with check (true);
alter policy outsource_partners_sel on public.outsource_partners using (true);
alter policy outsource_partners_upd on public.outsource_partners using (true) with check (true);
alter policy "manager delete payments" on public.payments using (is_manager());
alter policy "manager update payments" on public.payments using (is_manager()) with check (is_manager());
alter policy payments_insert on public.payments with check (true);
alter policy payments_select on public.payments using (true);
alter policy "staff add payments" on public.payments with check (is_active_staff());
alter policy "staff insert payments" on public.payments with check (is_active_staff());
alter policy "staff read payments" on public.payments using (is_active_staff());
alter policy "manager write price_list" on public.price_list using (is_manager()) with check (is_manager());
alter policy "staff add price_list" on public.price_list with check (is_active_staff());
alter policy "staff edit price_list" on public.price_list using (is_active_staff()) with check (is_active_staff());
alter policy "staff read price_list" on public.price_list using (is_active_staff());
alter policy "manager write profiles" on public.profiles using (is_manager()) with check (is_manager());
alter policy profiles_admin_all on public.profiles using (is_admin()) with check (is_admin());
alter policy profiles_select_all on public.profiles using (true);
alter policy profiles_update_own on public.profiles using ((id = auth.uid())) with check (((id = auth.uid()) AND (role = my_role())));
alter policy "self read profile" on public.profiles using ((auth.uid() = id));
alter policy "staff read profiles" on public.profiles using (true);
alter policy "push own select" on public.push_subscriptions using ((user_id = auth.uid()));
alter policy "push own write" on public.push_subscriptions using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
alter policy "staff all push" on public.push_subscriptions using (is_active_staff()) with check (is_active_staff());
alter policy admin_all on public.recurring_templates using (is_finance_admin()) with check (is_finance_admin());
alter policy read_all on public.recurring_templates using (true);
alter policy "reorder delete own" on public.reorder_actions using ((created_by = auth.uid()));
alter policy "reorder insert" on public.reorder_actions with check (true);
alter policy "reorder read" on public.reorder_actions using (true);
alter policy "staff delete reorder" on public.reorder_actions using (is_active_staff());
alter policy "staff insert reorder" on public.reorder_actions with check (is_active_staff());
alter policy "staff read reorder" on public.reorder_actions using (is_active_staff());
alter policy "staff read riders" on public.riders using (is_active_staff());
alter policy admin_all on public.salary_payments using (is_finance_admin()) with check (is_finance_admin());
alter policy task_comments_insert on public.task_comments with check (true);
alter policy task_comments_select on public.task_comments using (true);
alter policy tasks_delete on public.tasks using (true);
alter policy tasks_insert on public.tasks with check (((cardinality(COALESCE(assignee_ids, '{}'::uuid[])) <= 1) OR is_manager()));
alter policy tasks_select on public.tasks using (true);
alter policy tasks_update on public.tasks using (true) with check (true);
alter policy admin_all on public.vendors using (is_finance_admin()) with check (is_finance_admin());
alter policy read_all on public.vendors using (true);
alter policy weekly_subscriptions_del on public.weekly_subscriptions using (true);
alter policy weekly_subscriptions_ins on public.weekly_subscriptions with check (true);
alter policy weekly_subscriptions_sel on public.weekly_subscriptions using (true);
alter policy weekly_subscriptions_upd on public.weekly_subscriptions using (true) with check (true);
alter policy "finance delete" on storage.objects using (((bucket_id = 'finance-receipts'::text) AND is_finance_admin()));
alter policy "finance read" on storage.objects using ((bucket_id = 'finance-receipts'::text));
alter policy "finance upload" on storage.objects with check ((bucket_id = 'finance-receipts'::text));
alter policy "staff read order photo files" on storage.objects using (((bucket_id = 'order-photos'::text) AND is_active_staff()));
alter policy "staff upload order photo files" on storage.objects with check (((bucket_id = 'order-photos'::text) AND is_active_staff()));
alter policy "velto photos insert" on storage.objects with check ((bucket_id = 'order-photos'::text));
alter policy "velto photos select" on storage.objects using ((bucket_id = 'order-photos'::text));
alter policy "velto photos update" on storage.objects using ((bucket_id = 'order-photos'::text)) with check ((bucket_id = 'order-photos'::text));
-- cockpit_stats: restore the original function name.
drop function if exists public.cockpit_stats();
alter function public.cockpit_stats_unguarded() rename to cockpit_stats;
grant execute on function public.cockpit_stats() to authenticated;
commit;
