-- Velto notifications (docs/technical/RHYTHM.md, step 2): customers who allowed notifications on
-- their phone get order updates (picked up, ready, delivered) and, instead of an SMS, their
-- reminder.
--
--   website_push_keys   the VAPID key pair, generated by the website server on first use
--   website_push_subs   one row per browser that allowed notifications: who it belongs to
--                       (website login and/or Ops customer, phone) and what it wants
--   website_push_sent   order updates already sent (order + status), so none goes twice
--
-- A subscription is saved only by the website server: for a signed-in customer (their proven
-- phone) or from a reminder link (the phone the SMS went to). Service role only.
-- Requires website_rhythm.sql and website_identity_claim.sql (portal_proven_phone). Idempotent.

create table if not exists public.website_push_keys (
  id          smallint primary key default 1 check (id = 1),
  public_key  text not null check (public_key ~ '^[A-Za-z0-9_-]{80,100}$'),
  private_jwk text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.website_push_subs (
  endpoint      text primary key check (endpoint ~ '^https://' and char_length(endpoint) <= 1000),
  p256dh        text not null check (p256dh ~ '^[A-Za-z0-9_-]{80,100}$'),
  auth          text not null check (auth ~ '^[A-Za-z0-9_-]{16,32}$'),
  auth_user_id  uuid references auth.users (id) on delete cascade,
  customer_id   uuid references public.customers (id) on delete set null,
  phone         text check (phone is null or phone ~ '^01[3-9][0-9]{8}$'),
  lang          text not null default 'bn' check (lang in ('bn', 'en')),
  order_updates boolean not null default true,
  reminders     boolean not null default true,
  user_agent    text check (user_agent is null or char_length(user_agent) <= 300),
  failures      smallint not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_sent_at  timestamptz
);
create index if not exists website_push_subs_customer_idx on public.website_push_subs (customer_id) where active;
create index if not exists website_push_subs_phone_idx on public.website_push_subs (phone) where active;
create index if not exists website_push_subs_user_idx on public.website_push_subs (auth_user_id) where active;

create table if not exists public.website_push_sent (
  order_id uuid not null references public.orders (id) on delete cascade,
  status   text not null,
  sent_at  timestamptz not null default now(),
  primary key (order_id, status)
);

alter table public.website_push_keys enable row level security;
alter table public.website_push_subs enable row level security;
alter table public.website_push_sent enable row level security;
revoke all on public.website_push_keys, public.website_push_subs, public.website_push_sent from public, anon, authenticated, service_role;

-- Reminders can now go by push too.
alter table public.website_rhythm_touches drop constraint if exists website_rhythm_touches_channel_check;
alter table public.website_rhythm_touches add constraint website_rhythm_touches_channel_check check (channel in ('sms', 'push', 'staff', 'holdout'));
alter table public.website_rhythm_touches drop constraint if exists website_rhythm_touches_code_check;
alter table public.website_rhythm_touches add constraint website_rhythm_touches_code_check check (code is null or code ~ '^[A-Za-z0-9_-]{8}$');

-- website_rhythm_record: push rows get a code too (the notification opens the same one-tap page).
create or replace function public.website_rhythm_record(p_customer uuid, p_playbook text, p_channel text, p_lang text default 'bn')
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.website_rhythm;
  v_code text;
begin
  select * into r from public.website_rhythm where customer_id = p_customer;
  if r.customer_id is null then
    raise exception 'unknown customer' using errcode = 'P0002';
  end if;
  if p_channel in ('sms', 'push') then
    loop
      v_code := translate(encode(extensions.gen_random_bytes(6), 'base64'), '+/', '-_');
      exit when not exists (select 1 from public.website_rhythm_touches where code = v_code);
    end loop;
  end if;
  insert into public.website_rhythm_touches (customer_id, phone, playbook, channel, status, code, lang, segment, cadence_days,
                                              days_since, last_order, expires_at)
  values (r.customer_id, r.phone, p_playbook, p_channel,
          case when p_channel in ('sms', 'push') then 'sending' when p_channel = 'holdout' then 'holdout' else 'task' end,
          v_code, case when p_lang = 'en' then 'en' else 'bn' end, r.segment, r.cadence_days, r.days_since, r.last_order,
          case when p_channel in ('sms', 'push') then now() + interval '7 days' end);
  return v_code;
end;
$$;

-- The one-tap booking works from a push reminder as well as an SMS.
create or replace function public.website_rhythm_booking_data(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.website_rhythm_touches;
  cu public.customers;
  v_last text;
begin
  select * into t from public.website_rhythm_touches where code = p_code and channel in ('sms', 'push');
  if t.id is null or t.booked_at is not null or t.expires_at < now()
     or exists (select 1 from public.website_rhythm_optouts x where x.phone = t.phone) then
    return jsonb_build_object('ok', false);
  end if;
  select * into cu from public.customers where id = t.customer_id;
  select o.order_number into v_last from public.orders o
   where o.customer_id = t.customer_id and o.order_status is distinct from 'Cancelled' and o.order_date is not null
   order by o.order_date desc, o.created_at desc limit 1;
  return jsonb_build_object('ok', true, 'name', cu.name, 'phone', t.phone, 'address', cu.address, 'zone', cu.zone,
    'service', (select usual_service from public.website_rhythm where customer_id = t.customer_id), 'lastOrder', v_last);
end;
$$;

/* ---------- keys ---------- */

create or replace function public.website_push_keys_get()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object('publicKey', public_key, 'privateJwk', private_jwk) from public.website_push_keys where id = 1
$$;

-- First caller wins: a key pair generated by the website server is kept only if none exists yet.
create or replace function public.website_push_keys_init(p_public text, p_private text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.website_push_keys (id, public_key, private_jwk) values (1, p_public, p_private) on conflict (id) do nothing;
  return public.website_push_keys_get();
end;
$$;

-- Only the public key, for the page that asks for permission.
create or replace function public.website_push_public_key()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select public_key from public.website_push_keys where id = 1
$$;

/* ---------- subscriptions ---------- */

-- A signed-in customer allowed notifications: tied to their login, their linked Ops customer and
-- their proven phone. Re-saving the same browser updates it (and moves it to this login).
create or replace function public.website_push_save_for_user(p_auth_user_id uuid, p_endpoint text, p_p256dh text, p_auth text,
                                                             p_lang text, p_ua text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  a public.customer_accounts;
  v_phone text;
begin
  select * into a from public.customer_accounts where auth_user_id = p_auth_user_id;
  v_phone := coalesce(case when a.link_status = 'linked' then a.verified_phone end, public.portal_proven_phone(p_auth_user_id));
  insert into public.website_push_subs as s (endpoint, p256dh, auth, auth_user_id, customer_id, phone, lang, user_agent)
  values (p_endpoint, p_p256dh, p_auth, p_auth_user_id, case when a.link_status = 'linked' then a.customer_id end, v_phone,
          case when p_lang = 'en' then 'en' else 'bn' end, left(p_ua, 300))
  on conflict (endpoint) do update set p256dh = excluded.p256dh, auth = excluded.auth, auth_user_id = excluded.auth_user_id,
    customer_id = excluded.customer_id, phone = excluded.phone, lang = excluded.lang, user_agent = excluded.user_agent,
    active = true, failures = 0, updated_at = now();
  return public.website_push_status(p_auth_user_id);
end;
$$;

-- From a reminder link (the code proves the SMS reached this phone): tied to that Ops customer.
create or replace function public.website_push_save_for_code(p_code text, p_endpoint text, p_p256dh text, p_auth text, p_lang text, p_ua text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  t public.website_rhythm_touches;
begin
  select * into t from public.website_rhythm_touches where code = p_code and channel in ('sms', 'push');
  if t.id is null or t.expires_at < now() - interval '7 days' then
    return false;
  end if;
  insert into public.website_push_subs as s (endpoint, p256dh, auth, customer_id, phone, lang, user_agent)
  values (p_endpoint, p_p256dh, p_auth, t.customer_id, t.phone, case when p_lang = 'en' then 'en' else 'bn' end, left(p_ua, 300))
  on conflict (endpoint) do update set p256dh = excluded.p256dh, auth = excluded.auth,
    customer_id = excluded.customer_id, phone = excluded.phone, lang = excluded.lang, user_agent = excluded.user_agent,
    active = true, failures = 0, updated_at = now();
  return true;
end;
$$;

-- What the account page shows: is this login getting notifications, and which.
create or replace function public.website_push_status(p_auth_user_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'devices', count(*),
    'orderUpdates', coalesce(bool_or(order_updates), true),
    'reminders', coalesce(bool_or(reminders), true))
    from public.website_push_subs where auth_user_id = p_auth_user_id and active
$$;

create or replace function public.website_push_prefs(p_auth_user_id uuid, p_order_updates boolean, p_reminders boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.website_push_subs set order_updates = coalesce(p_order_updates, order_updates),
         reminders = coalesce(p_reminders, reminders), updated_at = now()
   where auth_user_id = p_auth_user_id and active;
  return public.website_push_status(p_auth_user_id);
end;
$$;

-- "Turn off" on this phone (the endpoint), or everywhere for this login (endpoint null).
create or replace function public.website_push_remove(p_auth_user_id uuid, p_endpoint text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.website_push_subs set active = false, updated_at = now()
   where auth_user_id = p_auth_user_id and (p_endpoint is null or endpoint = p_endpoint);
  return public.website_push_status(p_auth_user_id);
end;
$$;

-- The subscriptions to send to for one login (the test notification).
create or replace function public.website_push_targets_for_user(p_auth_user_id uuid)
returns table (endpoint text, p256dh text, auth text, lang text)
language sql
stable
security definer
set search_path = ''
as $$
  select s.endpoint, s.p256dh, s.auth, s.lang from public.website_push_subs s where s.auth_user_id = p_auth_user_id and s.active
$$;

-- The subscriptions that want reminders for one Ops customer (the evening run sends a push
-- instead of an SMS when there is one).
create or replace function public.website_push_targets_for_customer(p_customer uuid)
returns table (endpoint text, p256dh text, auth text, lang text)
language sql
stable
security definer
set search_path = ''
as $$
  select s.endpoint, s.p256dh, s.auth, s.lang
    from public.website_push_subs s
    left join public.customers cu on cu.id = p_customer
   where s.active and s.reminders
     and (s.customer_id = p_customer or (s.phone is not null and s.phone = public.portal_local_phone(cu.phone)))
$$;

-- After each send: success clears failures; a gone subscription (404/410) or 5 failures in a row stops it.
create or replace function public.website_push_result(p_endpoint text, p_ok boolean, p_gone boolean)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.website_push_subs
     set failures = case when p_ok then 0 else failures + 1 end,
         active = case when p_gone or (not p_ok and failures + 1 >= 5) then false else active end,
         last_sent_at = case when p_ok then now() else last_sent_at end,
         updated_at = now()
   where endpoint = p_endpoint
$$;

/* ---------- order updates ---------- */

-- Orders that reached Picked, Ready or Delivered (Ops' order_status_history) after the customer
-- allowed notifications and haven't been announced yet, with where to send them. Only the
-- order's current status counts (Picked then Ready within minutes sends only Ready), only the
-- last 2 days, and each order+status once: they are marked sent here, before sending.
create or replace function public.website_push_order_events(p_limit integer default 100)
returns table (order_id uuid, status text, order_number text, items integer, first_name text, targets jsonb)
language plpgsql
security definer
set search_path = ''
as $$
#variable_conflict use_column
begin
  return query
  with ev as (
    select distinct on (o.id) o.id eid, o.order_status st, o.order_number onum, o.total_items n, cu.name nm,
           public.portal_local_phone(cu.phone) ph, o.customer_id cid, h.changed_at chg
      from public.order_status_history h
      join public.orders o on o.id = h.order_id and o.order_status = h.new_status
      join public.customers cu on cu.id = o.customer_id
     where h.new_status in ('Picked', 'Ready', 'Delivered')
       and h.changed_at > now() - interval '2 days'
       and not exists (select 1 from public.website_push_sent x where x.order_id = o.id and x.status = o.order_status)
     order by o.id, h.changed_at desc
  ),
  t as (
    select ev.eid, jsonb_agg(jsonb_build_object('endpoint', s.endpoint, 'p256dh', s.p256dh, 'auth', s.auth, 'lang', s.lang)) tg
      from ev
      join public.website_push_subs s
        on s.active and s.order_updates and s.created_at < ev.chg
       and (s.customer_id = ev.cid or (s.phone is not null and s.phone = ev.ph))
     group by ev.eid
  ),
  picked as (
    insert into public.website_push_sent (order_id, status)
    select ev.eid, ev.st from ev join t on t.eid = ev.eid
     order by ev.chg
     limit least(greatest(coalesce(p_limit, 100), 1), 500)
    on conflict do nothing
    returning website_push_sent.order_id pid, website_push_sent.status pst
  )
  select ev.eid, ev.st, ev.onum, ev.n, nullif(public.portal_first_name(ev.nm), ''), t.tg
    from picked p join ev on ev.eid = p.pid and ev.st = p.pst join t on t.eid = ev.eid;
end;
$$;

/* ---------- grants ---------- */

revoke all on function public.website_push_keys_get() from public, anon, authenticated;
revoke all on function public.website_push_keys_init(text, text) from public, anon, authenticated;
revoke all on function public.website_push_public_key() from public, anon, authenticated;
revoke all on function public.website_push_save_for_user(uuid, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.website_push_save_for_code(text, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.website_push_status(uuid) from public, anon, authenticated;
revoke all on function public.website_push_prefs(uuid, boolean, boolean) from public, anon, authenticated;
revoke all on function public.website_push_remove(uuid, text) from public, anon, authenticated;
revoke all on function public.website_push_targets_for_user(uuid) from public, anon, authenticated;
revoke all on function public.website_push_targets_for_customer(uuid) from public, anon, authenticated;
revoke all on function public.website_push_result(text, boolean, boolean) from public, anon, authenticated;
revoke all on function public.website_push_order_events(integer) from public, anon, authenticated;
revoke all on function public.website_rhythm_record(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.website_rhythm_booking_data(text) from public, anon, authenticated;

grant execute on function public.website_push_keys_get() to service_role;
grant execute on function public.website_push_keys_init(text, text) to service_role;
grant execute on function public.website_push_public_key() to service_role;
grant execute on function public.website_push_save_for_user(uuid, text, text, text, text, text) to service_role;
grant execute on function public.website_push_save_for_code(text, text, text, text, text, text) to service_role;
grant execute on function public.website_push_status(uuid) to service_role;
grant execute on function public.website_push_prefs(uuid, boolean, boolean) to service_role;
grant execute on function public.website_push_remove(uuid, text) to service_role;
grant execute on function public.website_push_targets_for_user(uuid) to service_role;
grant execute on function public.website_push_targets_for_customer(uuid) to service_role;
grant execute on function public.website_push_result(text, boolean, boolean) to service_role;
grant execute on function public.website_push_order_events(integer) to service_role;
grant execute on function public.website_rhythm_record(uuid, text, text, text) to service_role;
grant execute on function public.website_rhythm_booking_data(text) to service_role;
