import { AuthNotice, authButton, authInput } from "@/components/account/AuthShell";
import { portalMe } from "@/lib/customer-portal";
import { requirePortalIdentity } from "@/lib/supabase/portal-server";
import { requestLinkAction, updateProfileAction } from "../../auth-actions";

type Params = Promise<Record<string, string | string[] | undefined>>;
const one = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
export const metadata = { title: "Profile | Velto Premium Laundry" };

export default async function ProfilePage({ searchParams }: { searchParams: Params }) {
  const { supabase, user } = await requirePortalIdentity("/account/profile");
  const [profile, params] = await Promise.all([portalMe(supabase), searchParams]);
  const phoneLocked = profile.link.status === "linked" || profile.link.status === "pending";
  return (
    <section className="container-page py-10 md:py-14" aria-labelledby="profile-title"><div className="max-w-2xl"><p className="t-label uppercase text-blue">Profile</p><h1 id="profile-title" className="mt-3 t-h1 text-navy">Saved details</h1><p className="mt-3 t-body text-body">These details can prefill your next pickup. You still confirm everything before sending a booking.</p>
      {one(params.state) === "saved" ? <div className="mt-6"><AuthNotice tone="success">Profile saved.</AuthNotice></div> : null}{one(params.state) === "email-verification" ? <div className="mt-6"><AuthNotice>Check your new email address to confirm the change.</AuthNotice></div> : null}{one(params.state) === "link-pending" ? <div className="mt-6"><AuthNotice>History-link request sent. Orders stay private until Velto verifies it.</AuthNotice></div> : null}{one(params.error) ? <div className="mt-6"><AuthNotice tone="error">We couldn’t save that change. Check the details and try again.</AuthNotice></div> : null}
      <form action={updateProfileAction} className="mt-8 space-y-5 border-t border-navy pt-6"><label className="block text-[14px] font-semibold text-navy">Name<input className={authInput} name="fullName" defaultValue={profile.fullName || profile.veltoProfile?.name || ""} autoComplete="name" required /></label><label className="block text-[14px] font-semibold text-navy">Email<input className={authInput} name="email" type="email" defaultValue={user.email || profile.email || ""} autoComplete="email" required /><span className="mt-2 block font-normal text-secondary">Changing email requires verification at the new address.</span></label><label className="block text-[14px] font-semibold text-navy">Phone<input className={`${authInput} disabled:bg-soft disabled:text-secondary`} name="phone" type="tel" defaultValue={profile.phone || profile.link.verifiedPhone || ""} autoComplete="tel" disabled={phoneLocked} /><span className="mt-2 block font-normal text-secondary">{phoneLocked ? "This phone is tied to history verification. It cannot be silently changed. Contact Velto if the number needs to change." : "Adding a phone does not unlock order history. Linking is a separate verification step."}</span></label><label className="block text-[14px] font-semibold text-navy">Address<input className={authInput} name="address" defaultValue={profile.address || profile.veltoProfile?.address || ""} autoComplete="street-address" /></label><label className="block text-[14px] font-semibold text-navy">Area<input className={authInput} name="area" defaultValue={profile.area || profile.veltoProfile?.zone || ""} placeholder="e.g. 11 or Uttara Sector 11" /></label><button className={`${authButton} md:w-auto`}>Save profile</button></form>
      <div className="mt-10 border-t border-line pt-7"><h2 className="t-h3 text-navy">Velto history</h2><p className="mt-2 t-body text-body">Status: <strong className="font-semibold text-navy">{profile.link.status === "linked" ? "Linked" : profile.link.status === "pending" ? "Verification pending" : "Not linked"}</strong></p>{profile.link.status === "linked" ? <p className="mt-2 t-small text-secondary">Verified phone: {profile.link.verifiedPhone || "Verified by Velto"}</p> : null}{profile.link.status !== "linked" && profile.link.status !== "pending" ? <form action={requestLinkAction}><button className="mt-5 min-h-11 rounded-md border border-navy px-5 text-[14px] font-semibold text-navy hover:bg-soft">Link your Velto history</button></form> : null}</div>
    </div></section>
  );
}
