import { mkdirSync, writeFileSync } from "node:fs";
import { requireTs } from "./lib/ts-require.mjs";

/**
 * Writes docs/content/BANGLA-REVIEW.md: every Bangla string next to its English
 * source, grouped by section, for the owner's copy review. Run: npm run i18n:review
 */
const { en } = requireTs("src/content/i18n/en.ts");
const { bn } = requireTs("src/content/i18n/bn.ts");
const { pagesEn } = requireTs("src/content/i18n/pages/en.ts");
const { pagesBn } = requireTs("src/content/i18n/pages/bn.ts");
const { SERVICE_PAGES, servicePages } = requireTs("src/content/services.ts");

const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k]) => !keys.includes(k)));

/** Service copy only: images, reviews, price columns and price-list item names are data, not copy. */
const serviceCopy = (pages) =>
  Object.fromEntries(
    pages.map((page) => [
      page.slug,
      {
        ...omit(page, ["slug", "image", "blocks"]),
        blocks: page.blocks.map((block) => ({
          ...omit(block, ["review", "image", "columns", "searchHint", "groups"]),
          ...(block.groups ? { groups: block.groups.map((g) => omit(g, ["names"])) } : {}),
        })),
      },
    ]),
  );

const rows = [];
/** Data fields and shared-question keys: identical in both languages, nothing to review. */
const NOT_COPY = /\.(?:primary|secondary|type|current)$|faq\.items\[\d+\]$/;
const walk = (a, b, path) => {
  if (typeof b === "string") return NOT_COPY.test(path) ? 0 : rows.push([path, typeof a === "string" ? a : "", b]);
  if (Array.isArray(b)) return b.forEach((v, i) => walk(a?.[i], v, `${path}[${i}]`));
  if (b && typeof b === "object") for (const k of Object.keys(b)) walk(a?.[k], b[k], path ? `${path}.${k}` : k);
};
walk(en, bn, "");
walk(pagesEn, pagesBn, "pages");
walk(serviceCopy(SERVICE_PAGES), serviceCopy(servicePages("bn")), "services");

const cell = (s) => s.replace(/\|/g, "\\|").replace(/⁠/g, "").replace(/\n/g, " ");
let md = `# Bangla website copy — for review

Status: **DRAFT, awaiting owner review.** Generated by \`npm run i18n:review\` from \`src/content/i18n/bn.ts\` (site chrome and homepage), \`src/content/i18n/pages/bn.ts\` (internal pages) and \`src/content/i18n/services.bn.ts\` (service pages); edit the Bangla there, not here.

- Standard Bangla (প্রমিত বাংলা), polite form (আপনি).
- Kept as they are: the brand (Velto, Velto Premium Laundry), WhatsApp / Google / Facebook, phone numbers, order numbers, street addresses and item names from the Ops price list (they must match Ops).
- Numbers, prices, dates and sectors use Bangla digits (৳৪৯৯, সেক্টর ১১).
- Customer reviews are never translated (the customer's own words).
- An empty English cell means the English text comes from elsewhere (for example image alt text in \`content/mock.ts\` or search titles in \`content/seo-routes.ts\`).

| Key | English | বাংলা |
| --- | --- | --- |
`;
let section = "";
for (const [key, eng, ban] of rows) {
  const parts = key.split(/[.[]/);
  const top = parts[0] === "pages" || parts[0] === "services" ? `${parts[0]}.${parts[1]}` : parts[0];
  if (top !== section) {
    section = top;
    md += `| **${top}** | | |\n`;
  }
  md += `| \`${key}\` | ${cell(eng)} | ${cell(ban)} |\n`;
}
mkdirSync("docs/content", { recursive: true });
writeFileSync("docs/content/BANGLA-REVIEW.md", md);
console.log(`Wrote docs/content/BANGLA-REVIEW.md (${rows.length} strings).`);
